### ISSUE TITLE
Performance and Productive use cases.

### ISSUE THREAD

**Issue by bd82** [w-y/ecma262-jison#30]
Hello again.

Is this project just a "learning experience" or something that is meant to be a "productive" library at some point?

The reason I am asking is because as a productive library I fear it may have great difficulty competing with hand crafted parsers (Acorn/Esprima/Cherow/...) in terms of performance.

See: [performance benchmark of parsing libraries](https://sap.github.io/chevrotain/performance/)
- Try on Chrome (V8)
- Jison is pretty slow
- Optimized hand crafted parsers will be faster than the one used in that benchmark.
- I am **guessing** a Jison based parser would have 3-5% of the performance of something like Acorn/Esprima...

**Comment by w-y** [comment]
@bd82 

It's mainly used for learning to build a parser in practice with lex/yacc tools (like jison) and the specifications. 

It's not for production env and the performance is bad.

Now I use jison-gho version (https://github.com/GerHobbelt/jison) since the project is still active.

The good thing is the rules of the specifications can be described and organized as code directly (like the bnf parts). You can just read the specifications(ecma, jsx)  and implement in a general way. It is easy to implement other parsers in this way.

**Comment by bd82** [comment]
If this is only a learning product then performance is not relevant. 

And your implementation of the [BNF rules](https://github.com/w-y/ecma262-jison/tree/master/src/bnf) indeed is highly modular and easy to understand. 👍
